PROMPT_MAPS = {
    "car": "car",
    "truck": "truck",
    "trailer": "trailer",
    "container": "trailer",
    "bus": "bus",
    "construction_vehicle": "construction_vehicle",
    "police vehicle": "emergency_vehicle",
    "emergency vehicle": "emergency_vehicle",
    "emergency_vehicle": "emergency_vehicle",
    "traffic_cone": "traffic_cone",
    "adult": "adult",
    "single little short youth children": "child",
    "child": "child",
    "law enforcement officer": "police_officer",
    "police_officer": "police_officer",
    "construction worker": "construction_worker",
    "construction_worker": "construction_worker",
    "laborer": "construction_worker",
    "bicycle bike": "bicycle",
    "bicycle": "bicycle",
    "narrow motorcycle": "motorcycle",
    "motorcycle": "motorcycle",
    "personal_mobility": "personal_mobility",
    "small kick scooter": "personal_mobility",
    "stroller": "stroller",
    "debris": "debris",
    "full trash bags": "debris",
    "barrier": "barrier",
    "pushable pullable garbage container": "pushable_pullable",
    "hand truck": "pushable_pullable",
    "pushable_pullable": "pushable_pullable",
}
